### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
title: El paraguas
description: Joven estudiante de nuevas tecnologias. Enfocado en aprendizaje de algoritmos en C y Python para pentesting.
baseurl: ""

# LANDING PAGE
username: Edu Martínez
typing_text: agachate y conoceme
email: edex357@gmail.com
github_username: JosephFouche
linkedin_username: eduardo-martínez-820960209

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: Sobre mi
about_me_description: >
  Estudiante permanente de TI.
  Enfocado en redes y pentesting. Abierto a pasantias, voluntariados y/o colaboraciones
  <a class="highlight-link" href="https://github.com/JosephFouche" target="_blank" rel="noreferrer"> Github </a>.
  Me podes encontrar en <a class="highlight-link" href="www.linkedin.com/in/eduardo-martínez-820960209" target="_blank" rel="noreferrer">JAMstack Themes</a>
  and on <a class="highlight-link" href="https://jekyll-themes.com/neumorphism/" target="_blank" rel="noreferrer">Jekyll Themes</a>.

# SKILLS SECTION
show_skills_card: true
skills_title: Skills

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://example.com/

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: true
os_projects_title: Open Source Projects

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: >
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.
  If you like this theme and want to use it for yourself, checkout the source code and the documentation at
  <a class="highlight-link" href="https://github.com/JosephFouche" target="_blank" rel="noreferrer"> Github </a>.

# GITHUB-METADATA
repository: JosephFouche/JosephFouche.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects:
      # Excluye todos los demás proyectos, dejando solo CSES-2025 visible
      - repo1
      - repo2
      - otro-proyecto
      # añade aquí todos los nombres de tus otros repositorios excepto "CSES-2025"

# GOOGLE-ANALYTICS
google-analytics:
  id: "UA-158757509-2"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json"
  ]
